/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.1.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionSanskrit_Hindi;
    QAction *actionEnglish;
    QAction *actionMarathi;
    QAction *actionNew;
    QAction *actionOpen;
    QAction *actionOpen_with;
    QAction *actionBook_1;
    QAction *actionPage_1;
    QAction *actionPage_2;
    QAction *actionClose_Book;
    QAction *actionClose_All_pages;
    QAction *actionClose_All_Books_and_Pages;
    QAction *actionSave;
    QAction *actionSave_As;
    QAction *actionSave_All;
    QAction *actionClose_All;
    QAction *actionPrint;
    QAction *actionExit;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionRemove;
    QAction *actionDelete;
    QAction *actionCut;
    QAction *actionCopy;
    QAction *actionPaste;
    QAction *actionSelect_All;
    QAction *actionGo_to_Line;
    QAction *actionFind_Replace_2;
    QAction *actionAll_Project;
    QAction *actionCurrent_File;
    QAction *actionCase_Sensitive;
    QAction *actionWhole_Words_Only;
    QAction *actionFind_Next;
    QAction *actionFind_Previous;
    QAction *actionFind_All;
    QAction *actionManage;
    QAction *actionReplace_Find;
    QAction *actionReplace_All;
    QAction *actionEdit_Page_Order;
    QAction *actionEdit_Page_Verifier;
    QAction *actionEdit_Sets;
    QAction *actionUI_Tour;
    QAction *actionTechnical_Support;
    QAction *actionReport_Bug;
    QAction *actionCheck_for_Updates;
    QAction *actionContact;
    QAction *actionAbout;
    QAction *actionShow_Left_Sidebar;
    QAction *actionShow_Right_Sidebar;
    QAction *actionViews;
    QAction *actionGrid_View;
    QAction *actionShow_Only_corrected_Pages;
    QAction *actionShow_All_Uncorrected_Pages;
    QAction *actionBold;
    QAction *actionSuperscript;
    QAction *actionSubscript;
    QAction *actionOpen_Book;
    QAction *actionAbout_Creator;
    QWidget *centralwidget;
    QTextEdit *textEdit;
    QMenuBar *menubar;
    QMenu *menuSelect_Language;
    QMenu *menuFile;
    QMenu *menuRecent_Book;
    QMenu *menuRecent_Page;
    QMenu *menuEdit;
    QMenu *menuFind_Replace;
    QMenu *menuAdvanced_Find;
    QMenu *menuAdvanced;
    QMenu *menuText_Formatting;
    QMenu *menuHelp;
    QMenu *menuView;
    QMenu *menuView_2;
    QStatusBar *statusbar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(800, 600);
        actionSanskrit_Hindi = new QAction(MainWindow);
        actionSanskrit_Hindi->setObjectName(QString::fromUtf8("actionSanskrit_Hindi"));
        actionEnglish = new QAction(MainWindow);
        actionEnglish->setObjectName(QString::fromUtf8("actionEnglish"));
        actionMarathi = new QAction(MainWindow);
        actionMarathi->setObjectName(QString::fromUtf8("actionMarathi"));
        actionNew = new QAction(MainWindow);
        actionNew->setObjectName(QString::fromUtf8("actionNew"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Images/new-document (1).png"), QSize(), QIcon::Normal, QIcon::Off);
        icon.addFile(QString::fromUtf8("new-document (1).png"), QSize(), QIcon::Normal, QIcon::On);
        actionNew->setIcon(icon);
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QString::fromUtf8("actionOpen"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Images/open (1).png"), QSize(), QIcon::Normal, QIcon::On);
        actionOpen->setIcon(icon1);
        actionOpen_with = new QAction(MainWindow);
        actionOpen_with->setObjectName(QString::fromUtf8("actionOpen_with"));
        actionBook_1 = new QAction(MainWindow);
        actionBook_1->setObjectName(QString::fromUtf8("actionBook_1"));
        actionPage_1 = new QAction(MainWindow);
        actionPage_1->setObjectName(QString::fromUtf8("actionPage_1"));
        actionPage_2 = new QAction(MainWindow);
        actionPage_2->setObjectName(QString::fromUtf8("actionPage_2"));
        actionClose_Book = new QAction(MainWindow);
        actionClose_Book->setObjectName(QString::fromUtf8("actionClose_Book"));
        actionClose_All_pages = new QAction(MainWindow);
        actionClose_All_pages->setObjectName(QString::fromUtf8("actionClose_All_pages"));
        actionClose_All_Books_and_Pages = new QAction(MainWindow);
        actionClose_All_Books_and_Pages->setObjectName(QString::fromUtf8("actionClose_All_Books_and_Pages"));
        actionSave = new QAction(MainWindow);
        actionSave->setObjectName(QString::fromUtf8("actionSave"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Images/floppy-disk.png"), QSize(), QIcon::Normal, QIcon::On);
        actionSave->setIcon(icon2);
        actionSave_As = new QAction(MainWindow);
        actionSave_As->setObjectName(QString::fromUtf8("actionSave_As"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/Images/save.png"), QSize(), QIcon::Normal, QIcon::On);
        actionSave_As->setIcon(icon3);
        actionSave_All = new QAction(MainWindow);
        actionSave_All->setObjectName(QString::fromUtf8("actionSave_All"));
        actionClose_All = new QAction(MainWindow);
        actionClose_All->setObjectName(QString::fromUtf8("actionClose_All"));
        actionPrint = new QAction(MainWindow);
        actionPrint->setObjectName(QString::fromUtf8("actionPrint"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionUndo = new QAction(MainWindow);
        actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/Images/undo.png"), QSize(), QIcon::Normal, QIcon::On);
        actionUndo->setIcon(icon4);
        actionRedo = new QAction(MainWindow);
        actionRedo->setObjectName(QString::fromUtf8("actionRedo"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/Images/redo.png"), QSize(), QIcon::Normal, QIcon::On);
        actionRedo->setIcon(icon5);
        actionRemove = new QAction(MainWindow);
        actionRemove->setObjectName(QString::fromUtf8("actionRemove"));
        actionDelete = new QAction(MainWindow);
        actionDelete->setObjectName(QString::fromUtf8("actionDelete"));
        actionCut = new QAction(MainWindow);
        actionCut->setObjectName(QString::fromUtf8("actionCut"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/Images/cut.png"), QSize(), QIcon::Normal, QIcon::On);
        actionCut->setIcon(icon6);
        actionCopy = new QAction(MainWindow);
        actionCopy->setObjectName(QString::fromUtf8("actionCopy"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/Images/copy.png"), QSize(), QIcon::Normal, QIcon::On);
        actionCopy->setIcon(icon7);
        actionPaste = new QAction(MainWindow);
        actionPaste->setObjectName(QString::fromUtf8("actionPaste"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/Images/paste.png"), QSize(), QIcon::Normal, QIcon::On);
        actionPaste->setIcon(icon8);
        actionSelect_All = new QAction(MainWindow);
        actionSelect_All->setObjectName(QString::fromUtf8("actionSelect_All"));
        actionGo_to_Line = new QAction(MainWindow);
        actionGo_to_Line->setObjectName(QString::fromUtf8("actionGo_to_Line"));
        actionFind_Replace_2 = new QAction(MainWindow);
        actionFind_Replace_2->setObjectName(QString::fromUtf8("actionFind_Replace_2"));
        actionAll_Project = new QAction(MainWindow);
        actionAll_Project->setObjectName(QString::fromUtf8("actionAll_Project"));
        actionCurrent_File = new QAction(MainWindow);
        actionCurrent_File->setObjectName(QString::fromUtf8("actionCurrent_File"));
        actionCase_Sensitive = new QAction(MainWindow);
        actionCase_Sensitive->setObjectName(QString::fromUtf8("actionCase_Sensitive"));
        actionWhole_Words_Only = new QAction(MainWindow);
        actionWhole_Words_Only->setObjectName(QString::fromUtf8("actionWhole_Words_Only"));
        actionFind_Next = new QAction(MainWindow);
        actionFind_Next->setObjectName(QString::fromUtf8("actionFind_Next"));
        actionFind_Previous = new QAction(MainWindow);
        actionFind_Previous->setObjectName(QString::fromUtf8("actionFind_Previous"));
        actionFind_All = new QAction(MainWindow);
        actionFind_All->setObjectName(QString::fromUtf8("actionFind_All"));
        actionManage = new QAction(MainWindow);
        actionManage->setObjectName(QString::fromUtf8("actionManage"));
        actionReplace_Find = new QAction(MainWindow);
        actionReplace_Find->setObjectName(QString::fromUtf8("actionReplace_Find"));
        actionReplace_All = new QAction(MainWindow);
        actionReplace_All->setObjectName(QString::fromUtf8("actionReplace_All"));
        actionEdit_Page_Order = new QAction(MainWindow);
        actionEdit_Page_Order->setObjectName(QString::fromUtf8("actionEdit_Page_Order"));
        actionEdit_Page_Verifier = new QAction(MainWindow);
        actionEdit_Page_Verifier->setObjectName(QString::fromUtf8("actionEdit_Page_Verifier"));
        actionEdit_Sets = new QAction(MainWindow);
        actionEdit_Sets->setObjectName(QString::fromUtf8("actionEdit_Sets"));
        actionUI_Tour = new QAction(MainWindow);
        actionUI_Tour->setObjectName(QString::fromUtf8("actionUI_Tour"));
        actionTechnical_Support = new QAction(MainWindow);
        actionTechnical_Support->setObjectName(QString::fromUtf8("actionTechnical_Support"));
        actionReport_Bug = new QAction(MainWindow);
        actionReport_Bug->setObjectName(QString::fromUtf8("actionReport_Bug"));
        actionCheck_for_Updates = new QAction(MainWindow);
        actionCheck_for_Updates->setObjectName(QString::fromUtf8("actionCheck_for_Updates"));
        actionContact = new QAction(MainWindow);
        actionContact->setObjectName(QString::fromUtf8("actionContact"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionShow_Left_Sidebar = new QAction(MainWindow);
        actionShow_Left_Sidebar->setObjectName(QString::fromUtf8("actionShow_Left_Sidebar"));
        actionShow_Right_Sidebar = new QAction(MainWindow);
        actionShow_Right_Sidebar->setObjectName(QString::fromUtf8("actionShow_Right_Sidebar"));
        actionViews = new QAction(MainWindow);
        actionViews->setObjectName(QString::fromUtf8("actionViews"));
        actionGrid_View = new QAction(MainWindow);
        actionGrid_View->setObjectName(QString::fromUtf8("actionGrid_View"));
        actionShow_Only_corrected_Pages = new QAction(MainWindow);
        actionShow_Only_corrected_Pages->setObjectName(QString::fromUtf8("actionShow_Only_corrected_Pages"));
        actionShow_All_Uncorrected_Pages = new QAction(MainWindow);
        actionShow_All_Uncorrected_Pages->setObjectName(QString::fromUtf8("actionShow_All_Uncorrected_Pages"));
        actionBold = new QAction(MainWindow);
        actionBold->setObjectName(QString::fromUtf8("actionBold"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/Images/bold (1).png"), QSize(), QIcon::Normal, QIcon::On);
        actionBold->setIcon(icon9);
        actionSuperscript = new QAction(MainWindow);
        actionSuperscript->setObjectName(QString::fromUtf8("actionSuperscript"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/Images/superscript (1).png"), QSize(), QIcon::Normal, QIcon::On);
        actionSuperscript->setIcon(icon10);
        actionSubscript = new QAction(MainWindow);
        actionSubscript->setObjectName(QString::fromUtf8("actionSubscript"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/Images/subscript (1).png"), QSize(), QIcon::Normal, QIcon::On);
        actionSubscript->setIcon(icon11);
        actionOpen_Book = new QAction(MainWindow);
        actionOpen_Book->setObjectName(QString::fromUtf8("actionOpen_Book"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/Images/open-book.png"), QSize(), QIcon::Normal, QIcon::On);
        actionOpen_Book->setIcon(icon12);
        actionAbout_Creator = new QAction(MainWindow);
        actionAbout_Creator->setObjectName(QString::fromUtf8("actionAbout_Creator"));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/Images/cv.png"), QSize(), QIcon::Normal, QIcon::On);
        actionAbout_Creator->setIcon(icon13);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        textEdit = new QTextEdit(centralwidget);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(50, 20, 581, 271));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 800, 26));
        menuSelect_Language = new QMenu(menubar);
        menuSelect_Language->setObjectName(QString::fromUtf8("menuSelect_Language"));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuRecent_Book = new QMenu(menuFile);
        menuRecent_Book->setObjectName(QString::fromUtf8("menuRecent_Book"));
        menuRecent_Page = new QMenu(menuFile);
        menuRecent_Page->setObjectName(QString::fromUtf8("menuRecent_Page"));
        menuEdit = new QMenu(menubar);
        menuEdit->setObjectName(QString::fromUtf8("menuEdit"));
        menuFind_Replace = new QMenu(menuEdit);
        menuFind_Replace->setObjectName(QString::fromUtf8("menuFind_Replace"));
        menuAdvanced_Find = new QMenu(menuFind_Replace);
        menuAdvanced_Find->setObjectName(QString::fromUtf8("menuAdvanced_Find"));
        menuAdvanced = new QMenu(menuEdit);
        menuAdvanced->setObjectName(QString::fromUtf8("menuAdvanced"));
        menuText_Formatting = new QMenu(menuEdit);
        menuText_Formatting->setObjectName(QString::fromUtf8("menuText_Formatting"));
        menuHelp = new QMenu(menubar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuView = new QMenu(menubar);
        menuView->setObjectName(QString::fromUtf8("menuView"));
        menuView_2 = new QMenu(menuView);
        menuView_2->setObjectName(QString::fromUtf8("menuView_2"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);
        toolBar = new QToolBar(MainWindow);
        toolBar->setObjectName(QString::fromUtf8("toolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, toolBar);

        menubar->addAction(menuSelect_Language->menuAction());
        menubar->addAction(menuFile->menuAction());
        menubar->addAction(menuEdit->menuAction());
        menubar->addAction(menuView->menuAction());
        menubar->addAction(menuHelp->menuAction());
        menuSelect_Language->addAction(actionSanskrit_Hindi);
        menuSelect_Language->addAction(actionEnglish);
        menuSelect_Language->addAction(actionMarathi);
        menuFile->addAction(actionNew);
        menuFile->addAction(actionOpen);
        menuFile->addAction(actionOpen_Book);
        menuFile->addAction(menuRecent_Book->menuAction());
        menuFile->addAction(menuRecent_Page->menuAction());
        menuFile->addSeparator();
        menuFile->addAction(actionClose_Book);
        menuFile->addAction(actionClose_All_pages);
        menuFile->addSeparator();
        menuFile->addAction(actionSave);
        menuFile->addAction(actionSave_As);
        menuFile->addAction(actionSave_All);
        menuFile->addSeparator();
        menuFile->addAction(actionClose_All);
        menuFile->addSeparator();
        menuFile->addAction(actionPrint);
        menuFile->addSeparator();
        menuFile->addAction(actionExit);
        menuRecent_Book->addAction(actionBook_1);
        menuRecent_Page->addAction(actionPage_1);
        menuRecent_Page->addAction(actionPage_2);
        menuEdit->addAction(actionUndo);
        menuEdit->addAction(actionRedo);
        menuEdit->addSeparator();
        menuEdit->addAction(actionRemove);
        menuEdit->addAction(actionCut);
        menuEdit->addAction(actionCopy);
        menuEdit->addAction(actionPaste);
        menuEdit->addAction(actionDelete);
        menuEdit->addSeparator();
        menuEdit->addAction(menuText_Formatting->menuAction());
        menuEdit->addSeparator();
        menuEdit->addAction(actionSelect_All);
        menuEdit->addSeparator();
        menuEdit->addAction(menuAdvanced->menuAction());
        menuEdit->addSeparator();
        menuEdit->addAction(menuFind_Replace->menuAction());
        menuEdit->addAction(actionGo_to_Line);
        menuEdit->addSeparator();
        menuEdit->addAction(actionEdit_Page_Order);
        menuEdit->addAction(actionEdit_Page_Verifier);
        menuEdit->addAction(actionEdit_Sets);
        menuFind_Replace->addAction(actionFind_Replace_2);
        menuFind_Replace->addAction(menuAdvanced_Find->menuAction());
        menuFind_Replace->addSeparator();
        menuFind_Replace->addAction(actionCase_Sensitive);
        menuFind_Replace->addAction(actionWhole_Words_Only);
        menuFind_Replace->addSeparator();
        menuFind_Replace->addAction(actionFind_Next);
        menuFind_Replace->addAction(actionFind_Previous);
        menuFind_Replace->addAction(actionReplace_Find);
        menuFind_Replace->addAction(actionReplace_All);
        menuAdvanced_Find->addAction(actionAll_Project);
        menuAdvanced_Find->addAction(actionCurrent_File);
        menuAdvanced->addAction(actionManage);
        menuText_Formatting->addAction(actionBold);
        menuText_Formatting->addAction(actionSuperscript);
        menuText_Formatting->addAction(actionSubscript);
        menuHelp->addAction(actionUI_Tour);
        menuHelp->addAction(actionTechnical_Support);
        menuHelp->addAction(actionReport_Bug);
        menuHelp->addSeparator();
        menuHelp->addAction(actionAbout_Creator);
        menuHelp->addAction(actionAbout);
        menuHelp->addAction(actionContact);
        menuHelp->addSeparator();
        menuHelp->addAction(actionCheck_for_Updates);
        menuView->addAction(actionShow_Left_Sidebar);
        menuView->addAction(actionShow_Right_Sidebar);
        menuView->addSeparator();
        menuView->addAction(menuView_2->menuAction());
        menuView_2->addAction(actionShow_Only_corrected_Pages);
        menuView_2->addAction(actionShow_All_Uncorrected_Pages);
        toolBar->addAction(actionNew);
        toolBar->addAction(actionOpen);
        toolBar->addAction(actionOpen_Book);
        toolBar->addAction(actionSave);
        toolBar->addAction(actionSave_As);
        toolBar->addSeparator();
        toolBar->addAction(actionUndo);
        toolBar->addAction(actionRedo);
        toolBar->addAction(actionCut);
        toolBar->addAction(actionCopy);
        toolBar->addAction(actionPaste);
        toolBar->addSeparator();
        toolBar->addAction(actionBold);
        toolBar->addAction(actionSuperscript);
        toolBar->addAction(actionSubscript);
        toolBar->addSeparator();
        toolBar->addAction(actionAbout_Creator);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MPad", nullptr));
        actionSanskrit_Hindi->setText(QCoreApplication::translate("MainWindow", "Sanskrit/Hindi", nullptr));
        actionEnglish->setText(QCoreApplication::translate("MainWindow", "English", nullptr));
        actionMarathi->setText(QCoreApplication::translate("MainWindow", "Marathi", nullptr));
        actionNew->setText(QCoreApplication::translate("MainWindow", "New", nullptr));
        actionOpen->setText(QCoreApplication::translate("MainWindow", "Open", nullptr));
        actionOpen_with->setText(QCoreApplication::translate("MainWindow", "Open with..", nullptr));
        actionBook_1->setText(QCoreApplication::translate("MainWindow", "Book 1", nullptr));
        actionPage_1->setText(QCoreApplication::translate("MainWindow", "Page 1", nullptr));
        actionPage_2->setText(QCoreApplication::translate("MainWindow", "Page 2", nullptr));
        actionClose_Book->setText(QCoreApplication::translate("MainWindow", "Close Book", nullptr));
        actionClose_All_pages->setText(QCoreApplication::translate("MainWindow", "Close All pages", nullptr));
        actionClose_All_Books_and_Pages->setText(QCoreApplication::translate("MainWindow", "Close Pages", nullptr));
        actionSave->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        actionSave_As->setText(QCoreApplication::translate("MainWindow", "Save As", nullptr));
        actionSave_All->setText(QCoreApplication::translate("MainWindow", "Save All", nullptr));
        actionClose_All->setText(QCoreApplication::translate("MainWindow", "Close All", nullptr));
        actionPrint->setText(QCoreApplication::translate("MainWindow", "Print", nullptr));
        actionExit->setText(QCoreApplication::translate("MainWindow", "Exit", nullptr));
        actionUndo->setText(QCoreApplication::translate("MainWindow", "Undo", nullptr));
        actionRedo->setText(QCoreApplication::translate("MainWindow", "Redo", nullptr));
        actionRemove->setText(QCoreApplication::translate("MainWindow", "Remove", nullptr));
        actionDelete->setText(QCoreApplication::translate("MainWindow", "Delete", nullptr));
        actionCut->setText(QCoreApplication::translate("MainWindow", "Cut", nullptr));
        actionCopy->setText(QCoreApplication::translate("MainWindow", "Copy ", nullptr));
        actionPaste->setText(QCoreApplication::translate("MainWindow", "Paste", nullptr));
        actionSelect_All->setText(QCoreApplication::translate("MainWindow", "Select All", nullptr));
        actionGo_to_Line->setText(QCoreApplication::translate("MainWindow", "Go to Line...", nullptr));
        actionFind_Replace_2->setText(QCoreApplication::translate("MainWindow", "Find/ Replace", nullptr));
        actionAll_Project->setText(QCoreApplication::translate("MainWindow", "All Project", nullptr));
        actionCurrent_File->setText(QCoreApplication::translate("MainWindow", "Current Page", nullptr));
        actionCase_Sensitive->setText(QCoreApplication::translate("MainWindow", "Case Sensitive ", nullptr));
        actionWhole_Words_Only->setText(QCoreApplication::translate("MainWindow", "Whole Words Only", nullptr));
        actionFind_Next->setText(QCoreApplication::translate("MainWindow", "Find Next", nullptr));
        actionFind_Previous->setText(QCoreApplication::translate("MainWindow", "Find Previous", nullptr));
        actionFind_All->setText(QCoreApplication::translate("MainWindow", "Find All", nullptr));
        actionManage->setText(QCoreApplication::translate("MainWindow", "Manage", nullptr));
        actionReplace_Find->setText(QCoreApplication::translate("MainWindow", "Replace and Find", nullptr));
        actionReplace_All->setText(QCoreApplication::translate("MainWindow", "Replace All", nullptr));
        actionEdit_Page_Order->setText(QCoreApplication::translate("MainWindow", "Edit Page Order", nullptr));
        actionEdit_Page_Verifier->setText(QCoreApplication::translate("MainWindow", "Edit Page Verifier", nullptr));
        actionEdit_Sets->setText(QCoreApplication::translate("MainWindow", "Edit Sets", nullptr));
        actionUI_Tour->setText(QCoreApplication::translate("MainWindow", "UI Tour", nullptr));
        actionTechnical_Support->setText(QCoreApplication::translate("MainWindow", "Technical Support ", nullptr));
        actionReport_Bug->setText(QCoreApplication::translate("MainWindow", "Report Bug...", nullptr));
        actionCheck_for_Updates->setText(QCoreApplication::translate("MainWindow", "Check for Updates", nullptr));
        actionContact->setText(QCoreApplication::translate("MainWindow", "Contact...", nullptr));
        actionAbout->setText(QCoreApplication::translate("MainWindow", "About MPad", nullptr));
        actionShow_Left_Sidebar->setText(QCoreApplication::translate("MainWindow", "Show Left Sidebar", nullptr));
        actionShow_Right_Sidebar->setText(QCoreApplication::translate("MainWindow", "Show Right Sidebar", nullptr));
        actionViews->setText(QCoreApplication::translate("MainWindow", "Views", nullptr));
        actionGrid_View->setText(QCoreApplication::translate("MainWindow", "Grid View", nullptr));
        actionShow_Only_corrected_Pages->setText(QCoreApplication::translate("MainWindow", "Show Only Corrected Pages", nullptr));
        actionShow_All_Uncorrected_Pages->setText(QCoreApplication::translate("MainWindow", "Show All Uncorrected Pages", nullptr));
        actionBold->setText(QCoreApplication::translate("MainWindow", "Bold", nullptr));
        actionSuperscript->setText(QCoreApplication::translate("MainWindow", "Superscript", nullptr));
        actionSubscript->setText(QCoreApplication::translate("MainWindow", "Subscript", nullptr));
        actionOpen_Book->setText(QCoreApplication::translate("MainWindow", "Open Book", nullptr));
        actionAbout_Creator->setText(QCoreApplication::translate("MainWindow", "About Creator", nullptr));
        menuSelect_Language->setTitle(QCoreApplication::translate("MainWindow", "Select Language", nullptr));
        menuFile->setTitle(QCoreApplication::translate("MainWindow", "File", nullptr));
        menuRecent_Book->setTitle(QCoreApplication::translate("MainWindow", "Recent Book", nullptr));
        menuRecent_Page->setTitle(QCoreApplication::translate("MainWindow", "Recent Page", nullptr));
        menuEdit->setTitle(QCoreApplication::translate("MainWindow", "Edit", nullptr));
        menuFind_Replace->setTitle(QCoreApplication::translate("MainWindow", "Find/Replace", nullptr));
        menuAdvanced_Find->setTitle(QCoreApplication::translate("MainWindow", "Advanced Find", nullptr));
        menuAdvanced->setTitle(QCoreApplication::translate("MainWindow", "Advanced", nullptr));
        menuText_Formatting->setTitle(QCoreApplication::translate("MainWindow", "Text Formatting", nullptr));
        menuHelp->setTitle(QCoreApplication::translate("MainWindow", "Help", nullptr));
        menuView->setTitle(QCoreApplication::translate("MainWindow", "View", nullptr));
        menuView_2->setTitle(QCoreApplication::translate("MainWindow", "View", nullptr));
        toolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
